# This file contains configuration parameters
PTGB_BUILD_LANGUAGE ?= 1

# In Release mode, every flag will be set to 0 by default.
# see: build_define_opt and BUILD_DEFINE_VARS in Makefile.base.cfg

# -----------------------------------------------------------------------------
# Debug profile overrides
# NOTE: if you want to add a new option,
# make sure to add it to the BUILD_DEFINE_VARS list in Makefile.base.cfg
# -----------------------------------------------------------------------------
ifeq ($(DEBUG_MODE),1)
	PRINT_LINK_DATA = 0
	INSTANT_TEXT_SPEED = 0
	IGNORE_GAME_PAK = 1
	IGNORE_GAME_PAK_SPRITES = 0
	IGNORE_LINK_CABLE = 1
	IGNORE_MG_E4_FLAGS = 1
	IGNORE_UNRECEIVED_PKMN = 0
	FORCE_TUTORIAL = 0
	DONT_REMOVE_PKMN = 0
	DONT_HIDE_INVALID_PKMN = 0
	IGNORE_DEX_COMPLETION = 0
	FORCE_ALL_CAUGHT = 1
	WRITE_CABLE_DATA_TO_SAVE = 0
	SHOW_DATA_PACKETS = 0
	DISPLAY_CONTROL_CHAR = 0
	PAYLOAD_EXPORT_TEST = 0
	DONT_TRANSFER_POKEMON_AT_INDEX_X = 0
	ENABLE_TEXT_DEBUG_SCREEN = 1
	DEBUG_PAYLOADS = 0
endif

# -----------------------------------------------------------------------------
# Debug target defaults
# -----------------------------------------------------------------------------
POKEMON_INDEX_TO_SKIP = 5
ENABLE_MATCH_PID = 1
ENABLE_DEBUG_SCREEN = 1

# Note: to override 
# - DEBUG_GAME
# - DEBUG_VERS
# - DEBUG_LANG
# set them in Makefile.base.cfg
# The problem is that the constants are defined in that file, but
# it's only getting included at the end of this file.
# That means the constant values don't exist until that include
# has been done.
# It's a Chicken-Egg problem, but this is the best solution I could come up with
# right now. If you have a better solution, please let me know!

# -----------------------------------------------------------------------------
# Memory options
# -----------------------------------------------------------------------------
USE_CUSTOM_MALLOC = 1
CUSTOM_MALLOC_POOL_SIZE = 8192

# Include base config from the same directory as this file
include $(dir $(lastword $(MAKEFILE_LIST)))Makefile.base.cfg
